### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [ascoos/awes#1]
Dear @ascoos team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by ascoos** [comment]
I don't think it's necessary to turn it into an organization. At least at the moment.

**Comment by Neustradamus** [comment]
Dear @ascoos team,

Thanks for your answer!

It is not possible to have a project with a personal account, can you reopen this ticket?
Do you need help to do the change?
It is free.

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear @ascoos team,

I wish you a Happy New Year 2025!

Have you progressed on this ticket?

GitHub TOS is here:
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements

**Comment by ascoos** [comment]
This account is a personal account and not a corporate account.
The "awes" you are referring to is a free application that I distribute through sourceforge and of course as long as github allows me to put some things here too..
I see no reason to convert my account to an organizational account.

If there is a problem with this repository or any other, tell me which ones have a problem so I can delete them.

**Comment by Neustradamus** [comment]
Dear @ascoos team: Yes, it is currently a personal account for a PROJECT.
It is for this, it is needed to convert, it is not linked with this repository but all repositories.
Important: It is free.

A personal account will be for "Drogidis Christos" :)

Two possibilities:
- Convert this personal account to organization but you need to create a real personal account before
- Rename this account for personal use and create the ascoos organization and move all ascoos related repositories into

Thanks in advance.

**Comment by Neustradamus** [comment]
Important: George Kourtidis, @DolceVii has already this personal account:
- https://github.com/DolceVii

**Comment by ascoos** [comment]
Okay, got it. I will do it soon.
